// capsule-attack.js — the adversaries the sealed capsule is measured against (2026-10).
//
// Every attacker here sees ONLY what the remote party sees: the capsule (opaque
// symbols and the worlds or the claim universe). None reads the key. They are
// given the generator's DESIGN (Kerckhoffs: the construction is public) — the
// learned attackers are trained on capsules generated by it — but not the
// secrets (the real slot, the symbol mapping, the witnessed set).
//
//   structural      closest-to-mean, odd-one-out, majority-vote, degree-sequence
//                   odd-one-out, size-prior, consistency (cyclic worlds cannot be real)
//   learned         a conditional-logit scorer and a small MLP scorer over per-world
//                   features, trained on generated capsules and scored on HELD-OUT ones
//   repeated-query  sees N capsules of the same situation (symbols and decoys
//                   resampled), aligns them and intersects (the leak the design warns of)
//
// An attacker returns a score per world; ties split evenly, so a guess is worth
// 1/|argmax| when the real world is among the maxima (exact expectation, no tie noise).

import { pid, closureOf } from "./capsule.js";

// ───────────────────────── what the remote sees ─────────────────────────

/** capsule → { n, shared, worlds:[{ n, pairs:[[a,b]], set:Set<pid> }] } over the capsule's own symbol order. */
export function viewOf(capsule) {
  if (capsule.task !== "worlds") throw new Error("viewOf is for world capsules");
  const worlds = [];
  if (capsule.construction === "symmetric-orbit") {
    for (const w of capsule.worlds) {
      const idx = Object.fromEntries(w.symbols.map((s, i) => [s, i]));
      const pairs = w.claims.map(([a, b]) => [idx[a], idx[b]]);
      worlds.push({ n: w.symbols.length, pairs, set: new Set(pairs.map(([a, b]) => pid(a, b, w.symbols.length))) });
    }
    return { n: capsule.worlds[0].symbols.length, shared: false, worlds };
  }
  const idx = Object.fromEntries(capsule.events.map((s, i) => [s, i]));
  const n = capsule.events.length;
  for (const w of capsule.worlds) {
    const pairs = w.claims.map(([a, b]) => [idx[a], idx[b]]);
    worlds.push({ n, pairs, set: new Set(pairs.map(([a, b]) => pid(a, b, n))) });
  }
  return { n, shared: true, worlds };
}

const symdiff = (A, B) => { let c = 0; for (const x of A) if (!B.has(x)) c++; for (const x of B) if (!A.has(x)) c++; return c; };
const jaccard = (A, B) => { let i = 0; for (const x of A) if (B.has(x)) i++; const u = A.size + B.size - i; return u ? i / u : 1; };

/** A Weisfeiler–Leman-style isomorphism-class hash of a directed graph (an incomplete invariant: equal graphs always
 *  hash equal; unequal ones almost always differ). */
export function wlHash(n, pairs, rounds = 3) {
  const out = Array.from({ length: n }, () => []), inn = Array.from({ length: n }, () => []);
  for (const [a, b] of pairs) { out[a].push(b); inn[b].push(a); }
  let col = Array.from({ length: n }, (_, i) => `${out[i].length}/${inn[i].length}`);
  for (let r = 0; r < rounds; r++) col = col.map((c, i) => `${c}|${out[i].map((j) => col[j]).sort().join(",")}|${inn[i].map((j) => col[j]).sort().join(",")}`).map(shortHash);
  return col.slice().sort().join(".");
}
function shortHash(s) { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0).toString(36); }

function longestPath(n, pairs) {
  const adj = Array.from({ length: n }, () => []);
  for (const [a, b] of pairs) adj[a].push(b);
  const memo = new Array(n).fill(-1);
  const go = (u) => { if (memo[u] >= 0) return memo[u]; memo[u] = 0; let b = 0; for (const v of adj[u]) b = Math.max(b, 1 + go(v)); return (memo[u] = b); };
  let best = 0; for (let u = 0; u < n; u++) best = Math.max(best, go(u)); return best;
}
function components(n, pairs) {
  const p = [...Array(n).keys()]; const f = (x) => (p[x] === x ? x : (p[x] = f(p[x])));
  for (const [a, b] of pairs) p[f(a)] = f(b);
  const touched = new Set(pairs.flat()); return new Set([...touched].map(f)).size;
}

export const FEATURES = Object.freeze(["size", "touched", "acyclic", "derived", "longest", "components", "maxOut", "maxIn", "linked", "degOdd", "isoCount", "meanDist", "minDist", "maxDist", "majAgree", "support", "sizeRel", "slot"]);

/** Per-world feature matrix [K][F] from a view. Set-relative features are 0 when the worlds share no symbols (orbit). */
export function worldFeatures(view) {
  const K = view.worlds.length;
  const shared = view.shared;
  const base = view.worlds.map((w) => {
    const deg = new Array(w.n).fill(0), od = new Array(w.n).fill(0), id = new Array(w.n).fill(0);
    for (const [a, b] of w.pairs) { deg[a]++; deg[b]++; od[a]++; id[b]++; }
    const cl = closureOf(w.n, w.pairs);
    const linked = w.pairs.length ? w.pairs.filter(([a, b]) => deg[a] + deg[b] >= 3).length / w.pairs.length : 0;
    return { size: w.pairs.length, touched: deg.filter((d) => d > 0).length, acyclic: cl.acyclic ? 1 : 0, derived: cl.derived.length, longest: cl.acyclic ? longestPath(w.n, w.pairs) : 0, comps: components(w.n, w.pairs), maxOut: Math.max(0, ...od), maxIn: Math.max(0, ...id), linked, degSeq: deg.slice().sort((x, y) => y - x), hash: wlHash(w.n, w.pairs) };
  });
  const meanSize = base.reduce((s, b) => s + b.size, 0) / K;
  const medSeq = base[0].degSeq.map((_, j) => { const c = base.map((b) => b.degSeq[j]).sort((x, y) => x - y); return c[Math.floor(c.length / 2)]; });
  const freq = new Map();
  if (shared) for (const w of view.worlds) for (const x of w.set) freq.set(x, (freq.get(x) || 0) + 1);
  const maj = new Set([...freq].filter(([, c]) => c * 2 > K).map(([x]) => x));
  return base.map((b, i) => {
    const w = view.worlds[i];
    let mean = 0, mn = Infinity, mx = 0;
    if (shared) { for (let j = 0; j < K; j++) if (j !== i) { const d = symdiff(w.set, view.worlds[j].set); mean += d; mn = Math.min(mn, d); mx = Math.max(mx, d); } mean /= Math.max(1, K - 1); } else { mn = 0; }
    const sup = shared && w.set.size ? [...w.set].reduce((s, x) => s + freq.get(x), 0) / (w.set.size * K) : 0;
    return [b.size, b.touched, b.acyclic, b.derived, b.longest, b.comps, b.maxOut, b.maxIn, b.linked, b.degSeq.reduce((s, d, j) => s + Math.abs(d - medSeq[j]), 0), base.filter((o) => o.hash === b.hash).length - 1,
      mean, shared ? mn : 0, mx, shared ? -symdiff(w.set, maj) : 0, sup, b.size - meanSize, i / K];
  });
}

// ───────────────────────── structural attackers ─────────────────────────

const F = Object.fromEntries(FEATURES.map((n, i) => [n, i]));
/** name → (view, X) → score per world (higher = more likely real). `priorMeanSize` is the generator's published mean. */
export const STRUCTURAL = Object.freeze({
  centroid: (v, X) => X.map((r) => -r[F.meanDist]),                         // closest to the others
  outlier: (v, X) => X.map((r) => r[F.meanDist]),                           // the odd one out
  majority: (v, X) => X.map((r) => r[F.majAgree]),                          // closest to the per-claim majority world
  support: (v, X) => X.map((r) => r[F.support]),                            // claims most shared with other worlds
  "degree-odd": (v, X) => X.map((r) => r[F.degOdd]),                        // degree sequence differs most from the median
  "degree-typical": (v, X) => X.map((r) => -r[F.degOdd]),
  consistency: (v, X) => X.map((r) => r[F.acyclic]),                        // a cyclic world cannot be the witnessed one
  "size-prior": (v, X, ctx) => X.map((r) => -Math.abs(r[F.size] - (ctx?.priorMeanSize ?? 4))),
  "first-slot": (v, X) => X.map((r, i) => (i === 0 ? 1 : 0)),               // position bias
});

/** Expected identification of a score vector: ties split evenly. */
export function tieAware(scores, real) {
  let mx = -Infinity; for (const s of scores) if (s > mx) mx = s;
  const top = scores.map((s, i) => (Math.abs(s - mx) < 1e-12 ? i : -1)).filter((i) => i >= 0);
  return top.includes(real) ? 1 / top.length : 0;
}

/** Wilson interval for k/n (k may be fractional from tie-splitting: the effective count). */
export function wilson(k, n, z = 1.96) {
  const p = k / n, d = 1 + (z * z) / n, c = (p + (z * z) / (2 * n)) / d, h = (z * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n))) / d;
  return { p, lo: Math.max(0, c - h), hi: Math.min(1, c + h), n };
}

// ───────────────────────── learned attackers ─────────────────────────

/** Train a per-world scorer with a softmax over the K worlds of a capsule. hidden = 0 is a conditional logit; hidden > 0 an MLP.
 *  samples: [{ X:[K][F], y }]. Returns { score(X) → [K], trainAcc }. Deterministic given seed. */
export function trainScorer(samples, { hidden = 0, epochs = 120, lr = 0.02, l2 = 1e-4, batch = 128, seed = 1 } = {}) {
  const Fd = samples[0].X[0].length;
  let sum = new Array(Fd).fill(0), sq = new Array(Fd).fill(0), cnt = 0;
  for (const s of samples) for (const r of s.X) { cnt++; r.forEach((x, j) => { sum[j] += x; sq[j] += x * x; }); }
  const mu = sum.map((s) => s / cnt), sd = sq.map((q, j) => Math.sqrt(Math.max(1e-9, q / cnt - mu[j] ** 2)) || 1);
  const norm = (r) => r.map((x, j) => (x - mu[j]) / sd[j]);
  let a = seed >>> 0; const rnd = () => { a = (a + 0x6d2b79f5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
  const H = hidden;
  const W1 = H ? Array.from({ length: H }, () => Array.from({ length: Fd }, () => (rnd() - 0.5) * 0.4)) : null;
  const b1 = H ? new Array(H).fill(0) : null;
  const w2 = Array.from({ length: H || Fd }, () => (rnd() - 0.5) * 0.2);
  // Adam state
  const params = [];
  if (H) { W1.forEach((row) => params.push(row)); params.push(b1); }
  params.push(w2);
  const m = params.map((p) => new Array(p.length).fill(0)), v = params.map((p) => new Array(p.length).fill(0));
  let step = 0;
  const forward = (x) => { if (!H) return { s: w2.reduce((s, w, j) => s + w * x[j], 0) }; const h = W1.map((row, k) => Math.tanh(row.reduce((s, w, j) => s + w * x[j], 0) + b1[k])); return { s: w2.reduce((s, w, k) => s + w * h[k], 0), h }; };
  const grads = params.map((p) => new Array(p.length).fill(0));
  const idx = samples.map((_, i) => i);
  for (let ep = 0; ep < epochs; ep++) {
    for (let i = idx.length - 1; i > 0; i--) { const j = Math.floor(rnd() * (i + 1)); [idx[i], idx[j]] = [idx[j], idx[i]]; }
    for (let off = 0; off < idx.length; off += batch) {
      grads.forEach((g) => g.fill(0));
      const chunk = idx.slice(off, off + batch);
      for (const si of chunk) {
        const { X, y } = samples[si];
        const xs = X.map(norm), fw = xs.map(forward);
        const mx = Math.max(...fw.map((f) => f.s)); const ex = fw.map((f) => Math.exp(f.s - mx)); const z = ex.reduce((p, q) => p + q, 0);
        fw.forEach((f, k) => {
          const d = ex[k] / z - (k === y ? 1 : 0);
          if (!H) { for (let j = 0; j < Fd; j++) grads[0][j] += d * xs[k][j]; }
          else {
            for (let u = 0; u < H; u++) {
              const dh = d * w2[u] * (1 - f.h[u] ** 2);
              for (let j = 0; j < Fd; j++) grads[u][j] += dh * xs[k][j];
              grads[H][u] += dh;
              grads[H + 1][u] += d * f.h[u];
            }
          }
        });
      }
      step++;
      params.forEach((p, pi) => { for (let j = 0; j < p.length; j++) { const g = grads[pi][j] / chunk.length + l2 * p[j]; m[pi][j] = 0.9 * m[pi][j] + 0.1 * g; v[pi][j] = 0.999 * v[pi][j] + 0.001 * g * g; p[j] -= (lr * (m[pi][j] / (1 - 0.9 ** step))) / (Math.sqrt(v[pi][j] / (1 - 0.999 ** step)) + 1e-8); } });
    }
  }
  const score = (X) => X.map((r) => forward(norm(r)).s);
  const trainAcc = samples.reduce((s, { X, y }) => s + tieAware(score(X), y), 0) / samples.length;
  return { score, trainAcc, hidden: H };
}

// ───────────────────────── repeated-query attacker ─────────────────────────

/** True event index of each capsule symbol position (the experiment knows it; the attacker may be given it as an ORACLE
 *  upper bound, or must recover it by `alignSearch`). */
export function truthMap(capsule, keyObj) {
  return capsule.events.map((s) => keyObj.eventOf[s]);
}

export function permuteSet(set, perm, n) { const out = new Set(); for (const x of set) out.add(perm[Math.floor(x / n)] * n + perm[x % n]); return out; }

/** Recover an event correspondence from `view` to `ref` by local search: maximise the total best-match Jaccard between the
 *  permuted worlds of one and the worlds of the other. This is what an adversary WITHOUT the oracle can do. */
export function alignSearch(view, ref, rng, { restarts = 6, sweeps = 3 } = {}) {
  const n = view.n;
  const score = (perm) => { let s = 0; for (const w of view.worlds) { const pw = permuteSet(w.set, perm, n); let b = 0; for (const r of ref.worlds) b = Math.max(b, jaccard(pw, r.set)); s += b; } return s; };
  let best = null, bs = -1;
  for (let r = 0; r < restarts; r++) {
    const perm = [...Array(n).keys()];
    if (r > 0) for (let i = n - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1)); [perm[i], perm[j]] = [perm[j], perm[i]]; }
    let cur = score(perm), improved = true, sw = 0;
    while (improved && sw++ < sweeps * n) {
      improved = false;
      for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) {
        [perm[i], perm[j]] = [perm[j], perm[i]];
        const s = score(perm);
        if (s > cur + 1e-12) { cur = s; improved = true; } else [perm[i], perm[j]] = [perm[j], perm[i]];
      }
    }
    if (cur > bs) { bs = cur; best = perm.slice(); }
  }
  return best;
}

/**
 * The intersection attack. `views` = N views of capsules for the SAME situation (symbols and decoys resampled, or not).
 * Align every view onto views[0]; a world's score is the sum, over the other capsules, of its best match (Jaccard) to any
 * world there. The real world recurs in every capsule; resampled decoys mostly do not. Returns scores for views[0]'s worlds.
 * `maps` (optional) = per-view true symbol→event maps: the ORACLE alignment (an upper bound on the attacker).
 */
export function intersectionScores(views, { maps = null, rng = Math.random, alignmentLog = null } = {}) {
  const ref = views[0], n = ref.n;
  const scores = ref.worlds.map(() => 1);
  for (let i = 1; i < views.length; i++) {
    const v = views[i];
    let perm; // perm[symbol position in v] → symbol position in ref
    if (maps) { const inv = new Map(maps[0].map((e, p) => [e, p])); perm = maps[i].map((e) => inv.get(e)); }
    else perm = alignSearch(v, ref, rng);
    if (alignmentLog && maps) { const inv = new Map(maps[0].map((e, p) => [e, p])); const truth = maps[i].map((e) => inv.get(e)); alignmentLog.push(perm.every((x, k) => x === truth[k]) ? 1 : 0); }
    const aligned = v.worlds.map((w) => permuteSet(w.set, perm, n));
    ref.worlds.forEach((w, j) => { let b = 0; for (const a of aligned) b = Math.max(b, jaccard(w.set, a)); scores[j] += b; });
  }
  return scores;
}

/** An attribute attacker: estimate the size of the real world as the mean world size (the best it can do without the key
 *  when the worlds are exchangeable). Compare its error to the prior-only error. */
export const estimateRealSize = (view) => view.worlds.reduce((s, w) => s + w.pairs.length, 0) / view.worlds.length;
